name: Run Python Script

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
        submodules: 'recursive'
        persist-credentials: false
        fetch-depth: 0
        token: ${{ secrets.PAT }}

    - name: Pull changes
      run: |
        git config pull.rebase false
        git pull origin main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r assets/requirements.txt

    - name: Run script
      run: |
        python assets/Main.py assets/urls.json README.Template.md README.output.md

    - name: Commit & Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "akat5uki"
        git config --global user.email "40821810+akat5uki@users.noreply.github.com"
        git add .
        git commit -m "[Automated] README updated with new Random quote!"
        git push origin main